version: "3.8"

networks:
  workflow_engine_net:
    name: workflow_engine_net
    driver: bridge

volumes:
  mongo-data:


services:
  workflow-engine:
    container_name: workflow-engine
    build: .
    restart: unless-stopped
    ports:
      - '8080:8080'
    env_file:
      - .env.docker
    networks:
      - workflow_engine_net
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
    networks:
      - workflow_engine_net

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    hostname: kafka
    ports:
      - "9092:9092"
    networks:
      - workflow_engine_net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      TOPIC_AUTO_CREATE: 1
